[package]
name = "orchestrator"
version = "0.1.0"
edition = "2024"

[dependencies]
reqwest = "0.12.20"
serde = { version = "1.0.219", features = ["derive"] }
serde_json = "1.0.140"
serde_yaml = "0.9.34"
toml = "0.8.23"
